version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:18
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    ports:
      - "7071:7071"
      - "7072:7072"
      - "5173:5173" # Vite default
      - "9229:9229" # Debug port
      - "9230:9230" # Debug port 2

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
